spring:
  datasource:
    #    url: jdbc:h2:tcp://localhost/~/test    // local
    url: jdbc:h2:mem:jpa
    driver-class-name: org.h2.Driver
    username: sa
    password:
    initialize: true
  h2:
    console:
      enabled: true
#  sql:
#    init:
#      mode: always
#      schema-locations: classpath*:schema.sql


  jpa:
    #    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create #create update none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace